AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false
